x-wabot-base: &wabot-base
  build:
    context: .
    dockerfile: Dockerfile
  # 不要设置 container_name，支持多实例
  network_mode: host
  volumes:
    - ./AUTH:/app/AUTH:rw,Z
    - ./baileys:/app/baileys:ro,Z
    - ./logs:/app/logs:rw,Z
  environment: &wabot-env
    NODE_ENV: production
    WS_URL: 'ws://10.148.0.3:8088/ws/'
  healthcheck:
    test: ["CMD", "pgrep", "-f", "node index.js"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s
  deploy:
    resources:
      limits:
        cpus: '1.0'
        memory: 1G
      reservations:
        cpus: '0.25'
        memory: 256M
  restart: unless-stopped

services:
  wabot1:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 1

  wabot2:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 2

  wabot3:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 3

  wabot4:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 4

  wabot5:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 5

  wabot6:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 6

  wabot7:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 7

  wabot8:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 8

  wabot9:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 9

  wabot10:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 10

  wabot11:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 11

  wabot12:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 12

  wabot13:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 13

  wabot14:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 14

  wabot15:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 15

  wabot16:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 16

  wabot17:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 17

  wabot18:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 18

  wabot19:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 19

  wabot20:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 20

  wabot21:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 21

  wabot22:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 22

  wabot23:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 23
  wabot24:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 24

  wabot25:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 25

  wabot26:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 26
  wabot27:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 27

  wabot28:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 28
  wabot29:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 29
  wabot30:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 30
  wabot31:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 31
  wabot32:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 32

  wabot33:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 33

  wabot34:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 34

  wabot35:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 35