x-wabot-base: &wabot-base
  build:
    context: .
    dockerfile: Dockerfile
  # 不要设置 container_name，支持多实例
  network_mode: host
  volumes:
    - ./AUTH:/app/AUTH:rw
    - ./baileys:/app/baileys:ro
    - ./logs:/app/logs:rw
  environment: &wabot-env
    NODE_ENV: production
    WS_URL: 'ws://127.0.0.1:8001/ws'
  healthcheck:
    test: ["CMD", "pgrep", "-f", "node index.js"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s
  deploy:
    resources:
      limits:
        cpus: '1.0'
        memory: 1G
      reservations:
        cpus: '0.25'
        memory: 256M
  restart: unless-stopped

services:
  wabot1:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 1

  wabot2:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 2

  wabot3:
    <<: *wabot-base
    user: root
    environment:
      <<: *wabot-env
      DEVICE_ID: 3
