services:
  wabot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wabot-client
    # 使用主机网络模式，直接访问主机上的服务
    network_mode: host
    volumes:
      # 重要：映射 AUTH 目录到宿主机，保持 WhatsApp token 数据持久化
      - ./AUTH:/app/AUTH:rw
      # 共享 baileys 依赖目录
      - ./baileys:/app/baileys:ro
      # 可选：映射日志目录
      - ./logs:/app/logs:rw
    environment:
      - NODE_ENV=production
      - WS_URL=ws://127.0.0.1:8001/ws
    healthcheck:
      test: ["CMD", "pgrep", "-f", "node index.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

# 使用host网络模式时不需要自定义网络

# 可选：如果需要数据库，可以添加
# volumes:
#   wabot-data:
#     driver: local
